import React from "react";
import { LinkIcon } from "lucide-react";

interface HeadingProps {
  level: 1 | 2 | 3 | 4 | 5 | 6;
  children?: React.ReactNode;
  id?: string;
}

/**
 * Custom heading component that adds clickable anchor links
 * Uses the id generated by rehype-slug plugin
 */
export function HeadingComponent({
  level,
  children,
  id,
  ...props
}: HeadingProps & React.HTMLAttributes<HTMLHeadingElement>) {
  const Tag = `h${level}` as keyof React.JSX.IntrinsicElements;
  
  // Don't add anchor link if there's no id
  if (!id) {
    return React.createElement(Tag, props, children);
  }

  return React.createElement(
    Tag,
    { id, ...props, className: `group relative ${props.className || ""}` },
    <>
      {children}
      <a
        href={`#${id}`}
        className="ml-2 inline-flex items-center opacity-0 group-hover:opacity-100 transition-opacity"
        aria-label={`Link to ${children}`}
        onClick={(e) => {
          e.preventDefault();
          const element = document.getElementById(id);
          if (element) {
            element.scrollIntoView({ behavior: "smooth", block: "start" });
            window.history.pushState(null, "", `#${id}`);
          }
        }}
      >
        <LinkIcon className="h-4 w-4 text-text-secondary hover:text-text-primary" />
      </a>
    </>
  );
}

/**
 * Factory functions for each heading level
 */
export const h1Component = (props: React.HTMLAttributes<HTMLHeadingElement>) => (
  <HeadingComponent level={1} {...props} />
);

export const h2Component = (props: React.HTMLAttributes<HTMLHeadingElement>) => (
  <HeadingComponent level={2} {...props} />
);

export const h3Component = (props: React.HTMLAttributes<HTMLHeadingElement>) => (
  <HeadingComponent level={3} {...props} />
);

export const h4Component = (props: React.HTMLAttributes<HTMLHeadingElement>) => (
  <HeadingComponent level={4} {...props} />
);

export const h5Component = (props: React.HTMLAttributes<HTMLHeadingElement>) => (
  <HeadingComponent level={5} {...props} />
);

export const h6Component = (props: React.HTMLAttributes<HTMLHeadingElement>) => (
  <HeadingComponent level={6} {...props} />
);
